'use client';

/**
 * Admin Store — Purchasing.
 *
 * Three-panel strict-DESIGN.md surface (0px radius, no shadows, parchment/forest
 * hairlines, matte buttons). Tabs:
 *   • Suppliers       — list / create / edit / deactivate (soft-delete; FKs RESTRICT).
 *   • Purchase Orders — list → detail. Create a DRAFT PO with line items
 *                       (skuId, warehouse, orderedQty, unitCost rupees→paise,
 *                       lotNo). Submit (place) / cancel / receive lines (which
 *                       bumps stock server-side).
 *
 * Money: the UI accepts rupees and converts to INTEGER PAISE on submit
 * (₹ × 100, rounded). The create-PO line DTO field is `unitCostPaise`; the
 * receive DTO is `{ lines: [{ lineId, receivedQty }] }`. The api.ts method TS
 * shapes carry legacy field names (`unitCost`, `qty`, `poLineId`, `qtyReceived`)
 * so each mutating call is passed the correct DTO object cast through `any` to
 * satisfy the global ValidationPipe (whitelist + forbidNonWhitelisted).
 * Identity/actor is server-pinned from the JWT — never sent in the body.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import {
  Truck, Plus, ChevronRight, X, RefreshCw, Trash2, Pencil, Power, Search,
  FileText, PackageCheck, Ban, Send, ClipboardList, Building2,
} from 'lucide-react';
import { api } from '@/lib/api';
import Pagination from '@/components/store/Pagination';
import Money, { formatPaise } from '@/components/store/Money';
import SkuPicker from '@/components/store/SkuPicker';

// ─── Types ────────────────────────────────────────────────────────────────────

interface SupplierRow {
  id: string;
  name: string;
  code?: string | null;
  contactName?: string | null;
  email?: string | null;
  phone?: string | null;
  gstin?: string | null;
  city?: string | null;
  stateCode?: string | null;
  leadTimeDays?: number | null;
  status: 'ACTIVE' | 'INACTIVE';
  notes?: string | null;
}

interface PoListRow {
  id: string;
  poNumber: string;
  status: string;
  subtotal: number;
  taxTotal: number;
  grandTotal: number;
  autoGenerated?: boolean;
  createdAt: string;
  supplier?: { id: string; name: string; code?: string | null };
  warehouse?: { id: string; code: string; name: string };
  _count?: { lines: number };
}

interface PoLine {
  id: string;
  skuId: string;
  lotNo: number;
  orderedQty: number;
  receivedQty: number;
  unitCost: number;
  taxBps: number;
  sku?: { id: string; skuCode: string; name: string };
}

interface PoDetail extends PoListRow {
  notes?: string | null;
  submittedAt?: string | null;
  receivedAt?: string | null;
  lines: PoLine[];
}

type Tab = 'suppliers' | 'orders';
type OrdersPanel = 'list' | 'detail' | 'create';

const INPUT =
  'w-full border border-hairline bg-white px-4 py-3 text-sm text-ink outline-none focus:border-forest';
const INPUT_SM =
  'w-full border border-hairline bg-white px-3 py-2 text-sm text-ink outline-none focus:border-forest';
const LABEL = 'block text-[10px] uppercase tracking-widest text-ink/60 mb-2 font-bold';

const EMPTY_SUPPLIER = {
  name: '', code: '', contactName: '', email: '', phone: '', gstin: '',
  city: '', stateCode: '', leadTimeDays: '', notes: '',
};

// Canonical 15-char Indian GSTIN — same regex CreateSupplierDto/UpdateSupplierDto
// enforce, so a malformed value is caught at entry instead of after a 400.
// NOTE: the supplier DTO validates stateCode with @Matches(/^[0-9]{2}$/) (NOT the
// INDIAN_STATE_CODES allowlist used for warehouses), so the client mirrors that
// looser 2-digit check here to stay aligned with the backend contract.
const GSTIN_REGEX = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/;

// PO line SKU selection is served by the SkuPicker typeahead (GET /admin/store/skus)
// — any SKU is selectable by code/name/product, not just those on a loaded stock
// matrix page, so the previous matrix-derived directory (and its truncation cap)
// are gone.

interface DraftLine {
  skuId: string;
  /** Display label for the SkuPicker-resolved SKU (e.g. "ABC-001 — Widget"). */
  skuLabel: string;
  orderedQty: string;
  unitCostRupees: string;
  lotNo: string;
  taxBps: string;
}

const EMPTY_LINE: DraftLine = { skuId: '', skuLabel: '', orderedQty: '', unitCostRupees: '', lotNo: '', taxBps: '' };

export default function AdminPurchasingPage() {
  const [tab, setTab] = useState<Tab>('suppliers');

  // ── Suppliers ──────────────────────────────────────────────────────────────
  const [suppliers, setSuppliers] = useState<SupplierRow[]>([]);
  const [suppliersMeta, setSuppliersMeta] = useState({ total: 0, page: 1, totalPages: 1, limit: 50 });
  const [suppliersLoading, setSuppliersLoading] = useState(true);
  const [suppliersError, setSuppliersError] = useState<string | null>(null);
  const [supplierPage, setSupplierPage] = useState(1);
  const [supplierStatusFilter, setSupplierStatusFilter] = useState('');
  const [supplierSearch, setSupplierSearch] = useState('');
  const [supplierSearchInput, setSupplierSearchInput] = useState('');

  const [showSupplierForm, setShowSupplierForm] = useState(false);
  const [editingSupplier, setEditingSupplier] = useState<SupplierRow | null>(null);
  const [supplierForm, setSupplierForm] = useState({ ...EMPTY_SUPPLIER });

  // ── Purchase orders ──────────────────────────────────────────────────────────
  const [ordersPanel, setOrdersPanel] = useState<OrdersPanel>('list');
  const [orders, setOrders] = useState<PoListRow[]>([]);
  const [ordersMeta, setOrdersMeta] = useState({ total: 0, page: 1, totalPages: 1, limit: 50 });
  const [ordersLoading, setOrdersLoading] = useState(false);
  const [ordersLoaded, setOrdersLoaded] = useState(false);
  const [ordersError, setOrdersError] = useState<string | null>(null);
  const [orderPage, setOrderPage] = useState(1);
  const [orderStatusFilter, setOrderStatusFilter] = useState('');

  const [detail, setDetail] = useState<PoDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailError, setDetailError] = useState<string | null>(null);
  const [lastDetailId, setLastDetailId] = useState<string | null>(null);

  // ── Create-PO form ────────────────────────────────────────────────────────────
  const [warehouses, setWarehouses] = useState<{ id: string; code: string; name: string; isActive: boolean }[]>([]);
  const [refsError, setRefsError] = useState<string | null>(null);
  const [createForm, setCreateForm] = useState<{ supplierId: string; warehouseId: string; notes: string; lines: DraftLine[] }>(
    { supplierId: '', warehouseId: '', notes: '', lines: [{ ...EMPTY_LINE }] },
  );

  const [actionLoading, setActionLoading] = useState(false);

  // Receive working set: lineId -> qty string
  const [receiveQty, setReceiveQty] = useState<Record<string, string>>({});
  const [receiving, setReceiving] = useState(false);

  // ─── Loaders ───────────────────────────────────────────────────────────────

  const loadSuppliers = useCallback(async () => {
    setSuppliersLoading(true);
    setSuppliersError(null);
    try {
      const params: Record<string, string | number> = { page: supplierPage, limit: 50 };
      if (supplierStatusFilter) params.status = supplierStatusFilter;
      if (supplierSearch.trim()) params.search = supplierSearch.trim();
      const res = await api.adminListSuppliers(params);
      setSuppliers(res?.data ?? []);
      setSuppliersMeta(res?.meta ?? { total: 0, page: 1, totalPages: 1, limit: 50 });
    } catch (e: any) {
      setSuppliersError(e?.message || 'Failed to load suppliers');
      setSuppliers([]);
    } finally {
      setSuppliersLoading(false);
    }
  }, [supplierPage, supplierStatusFilter, supplierSearch]);

  const loadOrders = useCallback(async () => {
    setOrdersLoading(true);
    setOrdersError(null);
    try {
      const params: Record<string, string | number> = { page: orderPage, limit: 50 };
      if (orderStatusFilter) params.status = orderStatusFilter;
      const res = await api.adminListPurchaseOrders(params);
      setOrders(res?.data ?? []);
      setOrdersMeta(res?.meta ?? { total: 0, page: 1, totalPages: 1, limit: 50 });
      setOrdersLoaded(true);
    } catch (e: any) {
      setOrdersError(e?.message || 'Failed to load purchase orders');
      setOrders([]);
    } finally {
      setOrdersLoading(false);
    }
  }, [orderPage, orderStatusFilter]);

  // Receiving warehouses for the create-PO form. SKU selection per line is served
  // by the SkuPicker typeahead (GET /admin/store/skus), so no SKU directory is
  // pre-loaded here.
  const loadCreateRefs = useCallback(async () => {
    setRefsError(null);
    try {
      const wh = await api.adminListWarehouses(false);
      setWarehouses(Array.isArray(wh) ? wh : []);
    } catch (e: any) {
      setRefsError(e?.message || 'Failed to load warehouses for this form');
      setWarehouses([]);
    }
  }, []);

  useEffect(() => { loadSuppliers(); }, [loadSuppliers]);
  useEffect(() => {
    if (tab === 'orders' && ordersPanel === 'list') loadOrders();
  }, [tab, ordersPanel, loadOrders]);

  // Debounced supplier search.
  useEffect(() => {
    const t = setTimeout(() => { setSupplierPage(1); setSupplierSearch(supplierSearchInput); }, 350);
    return () => clearTimeout(t);
  }, [supplierSearchInput]);

  // ─── Supplier mutations ──────────────────────────────────────────────────────

  const openCreateSupplier = () => {
    setEditingSupplier(null);
    setSupplierForm({ ...EMPTY_SUPPLIER });
    setShowSupplierForm(true);
  };

  const openEditSupplier = (s: SupplierRow) => {
    setEditingSupplier(s);
    setSupplierForm({
      name: s.name || '',
      code: s.code || '',
      contactName: s.contactName || '',
      email: s.email || '',
      phone: s.phone || '',
      gstin: s.gstin || '',
      city: s.city || '',
      stateCode: s.stateCode || '',
      leadTimeDays: s.leadTimeDays != null ? String(s.leadTimeDays) : '',
      notes: s.notes || '',
    });
    setShowSupplierForm(true);
  };

  const submitSupplier = async () => {
    if (!supplierForm.name.trim()) { alert('Supplier name is required'); return; }
    if (supplierForm.stateCode.trim() && !/^[0-9]{2}$/.test(supplierForm.stateCode.trim())) {
      alert('State code must be a 2-digit GST state code'); return;
    }
    if (supplierForm.gstin.trim() && !GSTIN_REGEX.test(supplierForm.gstin.trim())) {
      alert('GSTIN format is invalid (expected 15 characters, e.g. 27AAACU1234A1Z5)'); return;
    }
    let leadTime: number | undefined;
    if (supplierForm.leadTimeDays.trim() !== '') {
      leadTime = Number(supplierForm.leadTimeDays);
      if (!Number.isInteger(leadTime) || leadTime < 0) { alert('Lead time must be a non-negative whole number of days'); return; }
    }
    setActionLoading(true);
    try {
      const body: Record<string, any> = { name: supplierForm.name.trim() };
      const opt = (k: keyof typeof supplierForm, v?: string) => {
        const val = (v ?? supplierForm[k]).toString().trim();
        if (val) body[k] = val;
      };
      opt('code'); opt('contactName'); opt('email'); opt('phone'); opt('gstin');
      opt('city'); opt('stateCode'); opt('notes');
      if (leadTime !== undefined) body.leadTimeDays = leadTime;

      if (editingSupplier) {
        await api.adminUpdateSupplier(editingSupplier.id, body);
      } else {
        await api.adminCreateSupplier(body as { name: string });
      }
      setShowSupplierForm(false);
      setEditingSupplier(null);
      await loadSuppliers();
    } catch (e: any) {
      alert(e?.message || 'Failed to save supplier');
    } finally {
      setActionLoading(false);
    }
  };

  const deactivateSupplier = async (s: SupplierRow) => {
    if (!confirm(`Deactivate supplier "${s.name}"? You cannot raise new purchase orders against it. History is preserved.`)) return;
    setActionLoading(true);
    try {
      await api.adminDeactivateSupplier(s.id);
      await loadSuppliers();
    } catch (e: any) {
      alert(e?.message || 'Failed to deactivate supplier');
    } finally {
      setActionLoading(false);
    }
  };

  const activeSuppliers = useMemo(() => suppliers.filter((s) => s.status === 'ACTIVE'), [suppliers]);

  // ─── PO: detail + lifecycle ──────────────────────────────────────────────────

  const openDetail = async (id: string) => {
    setOrdersPanel('detail');
    setDetailLoading(true);
    setDetailError(null);
    setLastDetailId(id);
    setReceiveQty({});
    try {
      const d = await api.adminGetPurchaseOrder(id);
      setDetail(d);
    } catch (e: any) {
      setDetail(null);
      setDetailError(e?.message || 'Failed to load purchase order');
    } finally {
      setDetailLoading(false);
    }
  };

  const refreshDetail = async () => {
    const id = detail?.id ?? lastDetailId;
    if (id) await openDetail(id);
  };

  const submitPo = async () => {
    if (!detail) return;
    if (!confirm(`Place purchase order ${detail.poNumber}? It moves from DRAFT to SUBMITTED.`)) return;
    setActionLoading(true);
    try {
      await api.adminSubmitPurchaseOrder(detail.id);
      await refreshDetail();
    } catch (e: any) {
      alert(e?.message || 'Failed to submit purchase order');
    } finally {
      setActionLoading(false);
    }
  };

  const cancelPo = async () => {
    if (!detail) return;
    if (!confirm(`Cancel purchase order ${detail.poNumber}? This is only possible while nothing has been received.`)) return;
    setActionLoading(true);
    try {
      await api.adminCancelPurchaseOrder(detail.id);
      await refreshDetail();
    } catch (e: any) {
      alert(e?.message || 'Failed to cancel purchase order');
    } finally {
      setActionLoading(false);
    }
  };

  const submitReceive = async () => {
    if (!detail) return;
    // Only consider rows the operator actually typed into (non-blank). Validate
    // each entered value explicitly so a fractional or non-numeric entry alerts
    // the operator rather than being silently dropped by the filter below.
    const entered = Object.entries(receiveQty).filter(([, qtyStr]) => qtyStr.trim() !== '');
    for (const [lineId, qtyStr] of entered) {
      const qty = Number(qtyStr);
      const poLine = detail.lines.find((x) => x.id === lineId);
      const label = poLine?.sku?.skuCode ?? 'a line';
      if (!Number.isFinite(qty) || !Number.isInteger(qty) || qty <= 0) {
        alert(`Receive quantity for ${label} must be a positive whole number`);
        return;
      }
    }
    const lines = entered.map(([lineId, qtyStr]) => ({ lineId, receivedQty: Number(qtyStr) }));
    if (lines.length === 0) {
      alert('Enter a positive whole-number quantity to receive for at least one line');
      return;
    }
    // Client-side over-receive guard (server enforces it too).
    for (const l of lines) {
      const poLine = detail.lines.find((x) => x.id === l.lineId);
      if (poLine) {
        const remaining = poLine.orderedQty - poLine.receivedQty;
        if (l.receivedQty > remaining) {
          alert(`Cannot receive ${l.receivedQty} for ${poLine.sku?.skuCode ?? 'a line'} — only ${remaining} remaining`);
          return;
        }
      }
    }
    if (!confirm(`Receive ${lines.length} line(s) into ${detail.warehouse?.code ?? 'the PO warehouse'}? This adds the quantities to stock.`)) return;
    setReceiving(true);
    try {
      // EXACT ReceivePoLinesDto: { lines: [{ lineId, receivedQty }] } — api.ts shape
      // uses { poLineId, qtyReceived }, so cast.
      await api.adminReceivePurchaseOrder(detail.id, { lines } as any);
      setReceiveQty({});
      await refreshDetail();
    } catch (e: any) {
      alert(e?.message || 'Failed to receive purchase order');
    } finally {
      setReceiving(false);
    }
  };

  // ─── PO: create ──────────────────────────────────────────────────────────────

  const openCreatePo = async () => {
    setCreateForm({ supplierId: '', warehouseId: '', notes: '', lines: [{ ...EMPTY_LINE }] });
    setOrdersPanel('create');
    await loadCreateRefs();
  };

  const updateLine = (idx: number, patch: Partial<DraftLine>) => {
    setCreateForm((f) => ({ ...f, lines: f.lines.map((l, i) => (i === idx ? { ...l, ...patch } : l)) }));
  };
  const addLine = () => setCreateForm((f) => ({ ...f, lines: [...f.lines, { ...EMPTY_LINE }] }));
  const removeLine = (idx: number) =>
    setCreateForm((f) => ({ ...f, lines: f.lines.length > 1 ? f.lines.filter((_, i) => i !== idx) : f.lines }));

  // Live PO total preview (paise).
  const draftTotals = useMemo(() => {
    let subtotal = 0;
    let taxTotal = 0;
    for (const l of createForm.lines) {
      const qty = Number(l.orderedQty);
      const rupees = Number(l.unitCostRupees);
      const bps = l.taxBps.trim() === '' ? 0 : Number(l.taxBps);
      if (!Number.isFinite(qty) || qty <= 0 || !Number.isFinite(rupees) || rupees < 0) continue;
      const unitPaise = Math.round(rupees * 100);
      const net = unitPaise * Math.floor(qty);
      subtotal += net;
      if (Number.isFinite(bps) && bps > 0) taxTotal += Math.floor((net * bps) / 10_000);
    }
    return { subtotal, taxTotal, grandTotal: subtotal + taxTotal };
  }, [createForm.lines]);

  const submitCreatePo = async () => {
    if (!createForm.supplierId) { alert('Select a supplier'); return; }
    if (!createForm.warehouseId) { alert('Select a receiving warehouse'); return; }

    const lines: any[] = [];
    const seen = new Set<string>();
    for (let i = 0; i < createForm.lines.length; i++) {
      const l = createForm.lines[i];
      if (!l.skuId.trim() && l.orderedQty.trim() === '' && l.unitCostRupees.trim() === '') continue; // skip blank row
      if (!l.skuId.trim()) { alert(`Line ${i + 1}: select a SKU`); return; }
      const qty = Number(l.orderedQty);
      if (!Number.isInteger(qty) || qty <= 0) { alert(`Line ${i + 1}: ordered quantity must be a positive whole number`); return; }
      const rupees = Number(l.unitCostRupees);
      if (!Number.isFinite(rupees) || rupees < 0) { alert(`Line ${i + 1}: unit cost must be zero or a positive amount in rupees`); return; }
      const unitCostPaise = Math.round(rupees * 100);

      let lotNo: number | undefined;
      if (l.lotNo.trim() !== '') {
        lotNo = Number(l.lotNo);
        if (!Number.isInteger(lotNo) || lotNo < 1) { alert(`Line ${i + 1}: lot number must be a positive whole number`); return; }
      }
      const effLot = lotNo ?? 1;
      const dedupeKey = `${l.skuId}:${effLot}`;
      if (seen.has(dedupeKey)) { alert(`Line ${i + 1}: duplicate SKU + lot — use a distinct lot number for the same SKU`); return; }
      seen.add(dedupeKey);

      let taxBps: number | undefined;
      if (l.taxBps.trim() !== '') {
        taxBps = Number(l.taxBps);
        if (!Number.isInteger(taxBps) || taxBps < 0 || taxBps > 10_000) { alert(`Line ${i + 1}: tax (bps) must be between 0 and 10000`); return; }
      }

      const line: any = { skuId: l.skuId.trim(), orderedQty: qty, unitCostPaise };
      if (lotNo !== undefined) line.lotNo = lotNo;
      if (taxBps !== undefined) line.taxBps = taxBps;
      lines.push(line);
    }

    if (lines.length === 0) { alert('Add at least one line item'); return; }

    setActionLoading(true);
    try {
      // EXACT CreatePurchaseOrderDto — api.ts line shape uses { qty, unitCost }, so cast.
      const body: any = {
        supplierId: createForm.supplierId,
        warehouseId: createForm.warehouseId,
        lines,
      };
      if (createForm.notes.trim()) body.notes = createForm.notes.trim();
      const created = await api.adminCreatePurchaseOrder(body);
      setOrdersPanel('detail');
      if (created?.id) {
        await openDetail(created.id);
      } else {
        setOrdersPanel('list');
        await loadOrders();
      }
    } catch (e: any) {
      alert(e?.message || 'Failed to create purchase order');
    } finally {
      setActionLoading(false);
    }
  };

  // ─── Helpers ───────────────────────────────────────────────────────────────

  const poStatusBadge = (status: string) => {
    const map: Record<string, string> = {
      DRAFT: 'bg-ink/5 text-ink/50 border-ink/15',
      SUBMITTED: 'bg-info/10 text-info border-info/25',
      PARTIALLY_RECEIVED: 'bg-marigold/15 text-warning border-marigold/40',
      RECEIVED: 'bg-success/10 text-success border-success/25',
      CANCELLED: 'bg-terracotta/10 text-terracotta border-terracotta/20',
    };
    return (
      <span className={`inline-block px-2 py-0.5 text-[9px] uppercase tracking-widest font-bold border ${map[status] || map.DRAFT}`}>
        {status.replace(/_/g, ' ')}
      </span>
    );
  };

  // ─── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="text-ink animate-fade-in px-4 sm:px-6 lg:px-8 py-8 sm:py-12 max-w-[1280px] 3xl:max-w-[1600px] mx-auto min-h-screen">
      {/* Header */}
      <header className="border-b border-hairline pb-8 mb-10 flex flex-wrap justify-between items-end gap-6">
        <div>
          <Link href="/admin/dashboard" className="text-sm uppercase tracking-widest text-forest font-medium mb-3 inline-block">
            ← Command Center
          </Link>
          <h1 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-bold leading-none">Purchasing</h1>
          <p className="text-ink/50 mt-2 font-serif italic">Suppliers &amp; purchase orders — receive into stock</p>
        </div>
      </header>

      {/* Tabs */}
      <div className="flex border-b border-hairline mb-8 overflow-x-auto">
        {([
          { key: 'suppliers' as Tab, label: 'Suppliers', icon: Building2 },
          { key: 'orders' as Tab, label: 'Purchase Orders', icon: ClipboardList },
        ]).map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            onClick={() => { setTab(key); if (key === 'orders') setOrdersPanel('list'); }}
            className={`px-6 py-3 text-[11px] uppercase tracking-widest font-bold transition-colors border-b-2 -mb-px flex items-center gap-2 shrink-0 whitespace-nowrap ${
              tab === key ? 'border-forest text-forest' : 'border-transparent text-ink/40 hover:text-ink'
            }`}
          >
            <Icon className="w-4 h-4" /> {label}
          </button>
        ))}
      </div>

      {/* ══════════ SUPPLIERS ══════════ */}
      {tab === 'suppliers' && (
        <section className="animate-fade-in">
          <div className="flex flex-wrap items-center gap-3 mb-6">
            <div className="relative flex-1 min-w-[240px]">
              <Search className="w-4 h-4 text-ink/30 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                value={supplierSearchInput}
                onChange={(e) => setSupplierSearchInput(e.target.value)}
                placeholder="Search name, code or GSTIN…"
                className="w-full border border-hairline bg-white pl-9 pr-4 py-2.5 text-sm text-ink outline-none focus:border-forest"
              />
            </div>
            <select
              value={supplierStatusFilter}
              onChange={(e) => { setSupplierPage(1); setSupplierStatusFilter(e.target.value); }}
              className="border border-hairline bg-white px-3 py-2.5 text-sm text-ink outline-none focus:border-forest"
            >
              <option value="">All statuses</option>
              <option value="ACTIVE">Active</option>
              <option value="INACTIVE">Inactive</option>
            </select>
            <button
              onClick={openCreateSupplier}
              className="px-6 py-2.5 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 transition-colors flex items-center gap-2"
            >
              <Plus className="w-4 h-4" /> New Supplier
            </button>
          </div>

          {suppliersError ? (
            <div className="border border-terracotta/30 bg-terracotta/5 p-6 text-terracotta text-sm flex items-center justify-between">
              <span>{suppliersError}</span>
              <button onClick={loadSuppliers} className="underline text-[10px] uppercase tracking-widest font-bold">Retry</button>
            </div>
          ) : suppliersLoading ? (
            <div className="p-12 text-center"><div className="w-6 h-6 border-2 border-forest border-t-transparent rounded-full animate-spin mx-auto" /></div>
          ) : suppliers.length === 0 ? (
            <div className="border border-hairline bg-white p-12 text-center text-ink/40">
              <Building2 className="w-8 h-8 mx-auto mb-3 opacity-40" />
              <p className="font-serif italic mb-4">No suppliers found.</p>
              <button onClick={openCreateSupplier} className="px-5 py-2.5 border border-forest text-forest text-[10px] uppercase tracking-widest font-bold hover:bg-forest hover:text-parchment transition-colors">Add First Supplier</button>
            </div>
          ) : (
            <div className="border border-hairline bg-white overflow-x-auto">
              <div className="min-w-[820px]">
              <div className="grid grid-cols-12 gap-4 px-6 py-3 bg-alabaster border-b border-hairline text-[9px] uppercase tracking-widest text-ink/40 font-bold">
                <div className="col-span-3">Name / Code</div>
                <div className="col-span-3">Contact</div>
                <div className="col-span-2">GSTIN</div>
                <div className="col-span-1 text-right">Lead</div>
                <div className="col-span-1">Status</div>
                <div className="col-span-2 text-right">Actions</div>
              </div>
              {suppliers.map((s) => (
                <div key={s.id} className={`grid grid-cols-12 gap-4 px-6 py-4 border-b border-hairline/50 hover:bg-alabaster/50 transition-colors items-center text-sm ${s.status !== 'ACTIVE' ? 'opacity-50' : ''}`}>
                  <div className="col-span-3">
                    <div className="font-bold">{s.name}</div>
                    {s.code && <div className="text-[10px] text-ink/40 font-mono">{s.code}</div>}
                  </div>
                  <div className="col-span-3 text-xs text-ink/60">
                    {s.contactName && <div>{s.contactName}</div>}
                    {s.email && <div className="text-[11px] text-ink/40 line-clamp-1">{s.email}</div>}
                    {!s.contactName && !s.email && <span className="text-ink/30">—</span>}
                  </div>
                  <div className="col-span-2 text-[11px] text-ink/50 font-mono line-clamp-1">{s.gstin || '—'}</div>
                  <div className="col-span-1 text-right tabular-nums text-ink/60">{s.leadTimeDays != null ? `${s.leadTimeDays}d` : '—'}</div>
                  <div className="col-span-1">
                    <span className={`inline-block px-2 py-0.5 text-[9px] uppercase tracking-widest font-bold border ${s.status === 'ACTIVE' ? 'bg-success/10 text-success border-success/25' : 'bg-ink/5 text-ink/40 border-ink/15'}`}>{s.status}</span>
                  </div>
                  <div className="col-span-2 flex justify-end gap-2">
                    <button
                      onClick={() => openEditSupplier(s)}
                      className="px-3 py-1.5 border border-hairline text-ink/60 text-[10px] uppercase tracking-widest font-bold hover:border-forest hover:text-forest transition-colors flex items-center gap-1.5"
                    >
                      <Pencil className="w-3 h-3" /> Edit
                    </button>
                    {s.status === 'ACTIVE' && (
                      <button
                        onClick={() => deactivateSupplier(s)}
                        disabled={actionLoading}
                        className="px-3 py-1.5 border border-hairline text-ink/60 text-[10px] uppercase tracking-widest font-bold hover:border-terracotta hover:text-terracotta transition-colors disabled:opacity-50 flex items-center gap-1.5"
                      >
                        <Power className="w-3 h-3" /> Off
                      </button>
                    )}
                  </div>
                </div>
              ))}
              </div>
            </div>
          )}

          {suppliersMeta.totalPages > 1 && (
            <div className="mt-6"><Pagination page={suppliersMeta.page} totalPages={suppliersMeta.totalPages} onPageChange={setSupplierPage} /></div>
          )}
        </section>
      )}

      {/* ══════════ PURCHASE ORDERS ══════════ */}
      {tab === 'orders' && ordersPanel === 'list' && (
        <section className="animate-fade-in">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
            <div className="flex items-center gap-3">
              <select
                value={orderStatusFilter}
                onChange={(e) => { setOrderPage(1); setOrderStatusFilter(e.target.value); }}
                className="border border-hairline bg-white px-3 py-2.5 text-sm text-ink outline-none focus:border-forest"
              >
                <option value="">All statuses</option>
                {['DRAFT', 'SUBMITTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'].map((s) => (
                  <option key={s} value={s}>{s.replace(/_/g, ' ')}</option>
                ))}
              </select>
              <button
                onClick={loadOrders}
                className="px-3 py-2.5 border border-hairline text-ink/60 hover:border-forest hover:text-forest transition-colors flex items-center gap-2 text-[10px] uppercase tracking-widest font-bold"
              >
                <RefreshCw className={`w-4 h-4 ${ordersLoading ? 'animate-spin' : ''}`} /> Refresh
              </button>
            </div>
            <button
              onClick={openCreatePo}
              className="px-6 py-2.5 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 transition-colors flex items-center gap-2"
            >
              <Plus className="w-4 h-4" /> New Purchase Order
            </button>
          </div>

          {ordersError ? (
            <div className="border border-terracotta/30 bg-terracotta/5 p-6 text-terracotta text-sm flex items-center justify-between">
              <span>{ordersError}</span>
              <button onClick={loadOrders} className="underline text-[10px] uppercase tracking-widest font-bold">Retry</button>
            </div>
          ) : ordersLoading && !ordersLoaded ? (
            <div className="p-12 text-center"><div className="w-6 h-6 border-2 border-forest border-t-transparent rounded-full animate-spin mx-auto" /></div>
          ) : orders.length === 0 ? (
            <div className="border border-hairline bg-white p-12 text-center text-ink/40">
              <ClipboardList className="w-8 h-8 mx-auto mb-3 opacity-40" />
              <p className="font-serif italic mb-4">No purchase orders yet.</p>
              <button onClick={openCreatePo} className="px-5 py-2.5 border border-forest text-forest text-[10px] uppercase tracking-widest font-bold hover:bg-forest hover:text-parchment transition-colors">Create First PO</button>
            </div>
          ) : (
            <div className="border border-hairline bg-white overflow-x-auto">
              <div className="min-w-[820px]">
              <div className="grid grid-cols-12 gap-4 px-6 py-3 bg-alabaster border-b border-hairline text-[9px] uppercase tracking-widest text-ink/40 font-bold">
                <div className="col-span-2">PO Number</div>
                <div className="col-span-3">Supplier</div>
                <div className="col-span-2">Warehouse</div>
                <div className="col-span-1 text-right">Lines</div>
                <div className="col-span-2 text-right">Total</div>
                <div className="col-span-2 text-right">Status</div>
              </div>
              {orders.map((o) => (
                <button
                  key={o.id}
                  onClick={() => openDetail(o.id)}
                  className="w-full text-left grid grid-cols-12 gap-4 px-6 py-4 border-b border-hairline/50 hover:bg-alabaster/50 transition-colors items-center text-sm"
                >
                  <div className="col-span-2">
                    <div className="font-bold font-mono text-xs">{o.poNumber}</div>
                    {o.autoGenerated && <div className="text-[8px] uppercase tracking-widest text-ink/30">Auto</div>}
                  </div>
                  <div className="col-span-3">
                    <div className="font-semibold text-xs">{o.supplier?.name ?? '—'}</div>
                    <div className="text-[10px] text-ink/40">{new Date(o.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
                  </div>
                  <div className="col-span-2 text-xs text-ink/60">{o.warehouse?.code ?? '—'}</div>
                  <div className="col-span-1 text-right tabular-nums text-ink/60">{o._count?.lines ?? '—'}</div>
                  <div className="col-span-2 text-right"><Money paise={o.grandTotal} className="font-bold text-forest text-xs" /></div>
                  <div className="col-span-2 flex justify-end items-center gap-2">
                    {poStatusBadge(o.status)}
                    <ChevronRight className="w-4 h-4 text-ink/30" />
                  </div>
                </button>
              ))}
              </div>
            </div>
          )}

          {ordersMeta.totalPages > 1 && (
            <div className="mt-6"><Pagination page={ordersMeta.page} totalPages={ordersMeta.totalPages} onPageChange={setOrderPage} /></div>
          )}
        </section>
      )}

      {/* ── PO DETAIL ── */}
      {tab === 'orders' && ordersPanel === 'detail' && (
        <section className="animate-fade-in">
          {/* Returning to 'list' re-triggers the lazy-load effect (tab==='orders' &&
              ordersPanel==='list'), so no explicit loadOrders() call is needed here. */}
          <button onClick={() => { setOrdersPanel('list'); setDetail(null); }} className="text-forest text-sm uppercase tracking-widest font-bold mb-6 inline-block">
            ← Back to Purchase Orders
          </button>

          {detailLoading ? (
            <div className="p-12 text-center"><div className="w-6 h-6 border-2 border-forest border-t-transparent rounded-full animate-spin mx-auto" /></div>
          ) : !detail ? (
            <div className="border border-terracotta/30 bg-terracotta/5 p-6 text-terracotta text-sm flex items-center justify-between">
              <span>{detailError || 'Failed to load purchase order.'}</span>
              {lastDetailId && (
                <button onClick={refreshDetail} className="underline text-[10px] uppercase tracking-widest font-bold">Retry</button>
              )}
            </div>
          ) : (
            <div className="space-y-8">
              {/* Header card */}
              <div className="border border-hairline bg-white p-8">
                <div className="flex items-start justify-between gap-6 flex-wrap">
                  <div>
                    <div className="flex items-center gap-3 mb-2">
                      <h2 className="font-serif text-3xl font-bold font-mono">{detail.poNumber}</h2>
                      {poStatusBadge(detail.status)}
                      {detail.autoGenerated && <span className="px-1.5 py-0.5 text-[8px] uppercase tracking-widest font-bold border bg-ink/5 text-ink/40 border-ink/15">Auto-generated</span>}
                    </div>
                    <div className="text-xs text-ink/60">Supplier: <strong>{detail.supplier?.name}</strong></div>
                    <div className="text-xs text-ink/60">Receiving warehouse: <strong>{detail.warehouse?.code} · {detail.warehouse?.name}</strong></div>
                    <div className="text-[11px] text-ink/40 mt-1">Raised {new Date(detail.createdAt).toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</div>
                    {detail.notes && <p className="text-xs text-ink/60 mt-3 max-w-md">{detail.notes}</p>}
                  </div>
                  <div className="flex gap-2 flex-wrap justify-end">
                    {detail.status === 'DRAFT' && (
                      <button onClick={submitPo} disabled={actionLoading} className="px-4 py-2 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 disabled:opacity-50 transition-colors flex items-center gap-2">
                        <Send className="w-3 h-3" /> Place Order
                      </button>
                    )}
                    {(detail.status === 'DRAFT' || detail.status === 'SUBMITTED') && (
                      <button onClick={cancelPo} disabled={actionLoading} className="px-4 py-2 border border-terracotta text-terracotta text-[10px] uppercase tracking-widest font-bold hover:bg-terracotta hover:text-white disabled:opacity-50 transition-colors flex items-center gap-2">
                        <Ban className="w-3 h-3" /> Cancel
                      </button>
                    )}
                    <button onClick={refreshDetail} disabled={detailLoading} className="px-4 py-2 border border-hairline text-ink/60 text-[10px] uppercase tracking-widest font-bold hover:border-forest hover:text-forest disabled:opacity-50 transition-colors flex items-center gap-2">
                      <RefreshCw className={`w-3 h-3 ${detailLoading ? 'animate-spin' : ''}`} /> Refresh
                    </button>
                  </div>
                </div>

                {/* Totals */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6 pt-6 border-t border-hairline">
                  <div>
                    <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold mb-1">Subtotal</div>
                    <Money paise={detail.subtotal} className="font-serif text-lg font-bold" />
                  </div>
                  <div>
                    <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold mb-1">Tax</div>
                    <Money paise={detail.taxTotal} className="font-serif text-lg font-bold" />
                  </div>
                  <div>
                    <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold mb-1">Grand Total</div>
                    <Money paise={detail.grandTotal} className="font-serif text-lg font-bold text-forest" />
                  </div>
                </div>
              </div>

              {/* Lines + receive */}
              <div className="border border-hairline bg-white">
                <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 border-b border-hairline">
                  <h3 className="font-serif text-lg font-bold flex items-center gap-2"><FileText className="w-5 h-5 text-forest/60" /> Line Items</h3>
                  {(detail.status === 'SUBMITTED' || detail.status === 'PARTIALLY_RECEIVED') && (
                    <button onClick={submitReceive} disabled={receiving} className="px-5 py-2.5 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 disabled:opacity-50 transition-colors flex items-center gap-2">
                      <PackageCheck className="w-4 h-4" /> {receiving ? 'Receiving…' : 'Receive Entered Qty'}
                    </button>
                  )}
                </div>

                <div className="overflow-x-auto">
                <div className="min-w-[760px]">
                <div className="grid grid-cols-12 gap-4 px-6 py-3 bg-alabaster border-b border-hairline text-[9px] uppercase tracking-widest text-ink/40 font-bold">
                  <div className="col-span-4">SKU</div>
                  <div className="col-span-1 text-right">Lot</div>
                  <div className="col-span-1 text-right">Ordered</div>
                  <div className="col-span-1 text-right">Received</div>
                  <div className="col-span-2 text-right">Unit Cost</div>
                  <div className="col-span-3 text-right">Receive Now</div>
                </div>

                {detail.lines.map((l) => {
                  const remaining = l.orderedQty - l.receivedQty;
                  const canReceive = (detail.status === 'SUBMITTED' || detail.status === 'PARTIALLY_RECEIVED') && remaining > 0;
                  return (
                    <div key={l.id} className="grid grid-cols-12 gap-4 px-6 py-4 border-b border-hairline/50 items-center text-sm">
                      <div className="col-span-4">
                        <div className="font-bold text-xs">{l.sku?.skuCode ?? l.skuId.slice(0, 8)}</div>
                        <div className="text-[10px] text-ink/40 line-clamp-1">{l.sku?.name}</div>
                      </div>
                      <div className="col-span-1 text-right tabular-nums text-ink/50">{l.lotNo}</div>
                      <div className="col-span-1 text-right tabular-nums font-semibold">{l.orderedQty}</div>
                      <div className="col-span-1 text-right tabular-nums">
                        <span className={l.receivedQty >= l.orderedQty ? 'text-success font-bold' : 'text-ink/60'}>{l.receivedQty}</span>
                      </div>
                      <div className="col-span-2 text-right">
                        <div className="tabular-nums text-xs">{formatPaise(l.unitCost)}</div>
                        {l.taxBps > 0 && <div className="text-[9px] text-ink/40">{(l.taxBps / 100).toFixed(2)}% tax</div>}
                      </div>
                      <div className="col-span-3 flex justify-end items-center gap-2">
                        {canReceive ? (
                          <>
                            <input
                              type="number"
                              min={0}
                              max={remaining}
                              step={1}
                              value={receiveQty[l.id] ?? ''}
                              onChange={(e) => setReceiveQty((m) => ({ ...m, [l.id]: e.target.value }))}
                              placeholder={`0 / ${remaining}`}
                              className="w-24 border border-hairline bg-white px-2 py-1.5 text-xs text-ink outline-none focus:border-forest text-right tabular-nums"
                            />
                            <span className="text-[9px] text-ink/30 whitespace-nowrap">of {remaining}</span>
                          </>
                        ) : remaining <= 0 ? (
                          <span className="text-[10px] uppercase tracking-widest text-success font-bold">Complete</span>
                        ) : (
                          <span className="text-[10px] uppercase tracking-widest text-ink/30">—</span>
                        )}
                      </div>
                    </div>
                  );
                })}
                </div>
                </div>
              </div>
            </div>
          )}
        </section>
      )}

      {/* ── PO CREATE ── */}
      {tab === 'orders' && ordersPanel === 'create' && (
        <section className="animate-fade-in">
          <button onClick={() => setOrdersPanel('list')} className="text-forest text-sm uppercase tracking-widest font-bold mb-6 inline-block">
            ← Back to Purchase Orders
          </button>

          <div className="border border-hairline bg-white p-4 sm:p-8 max-w-[900px]">
            <h2 className="font-serif text-2xl font-bold mb-6 flex items-center gap-2"><Truck className="w-5 h-5 text-forest/60" /> New Purchase Order</h2>

            {activeSuppliers.length === 0 && (
              <div className="border border-marigold/40 bg-marigold/10 p-4 mb-6 text-sm text-warning">
                No active suppliers. Create an active supplier first on the Suppliers tab.
              </div>
            )}

            {refsError && (
              <div className="border border-terracotta/30 bg-terracotta/5 p-4 mb-6 text-sm text-terracotta flex items-center justify-between gap-4">
                <span>{refsError}</span>
                <button onClick={loadCreateRefs} className="underline text-[10px] uppercase tracking-widest font-bold whitespace-nowrap">Retry</button>
              </div>
            )}

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
              <div>
                <label className={LABEL}>Supplier *</label>
                <select value={createForm.supplierId} onChange={(e) => setCreateForm({ ...createForm, supplierId: e.target.value })} className={INPUT}>
                  <option value="">Select supplier…</option>
                  {activeSuppliers.map((s) => <option key={s.id} value={s.id}>{s.name}{s.code ? ` (${s.code})` : ''}</option>)}
                </select>
              </div>
              <div>
                <label className={LABEL}>Receiving Warehouse *</label>
                <select value={createForm.warehouseId} onChange={(e) => setCreateForm({ ...createForm, warehouseId: e.target.value })} className={INPUT}>
                  <option value="">Select warehouse…</option>
                  {warehouses.filter((w) => w.isActive).map((w) => <option key={w.id} value={w.id}>{w.code} · {w.name}</option>)}
                </select>
                <p className="text-[9px] text-ink/35 mt-1">All lines are received into this single warehouse.</p>
              </div>
            </div>

            {/* Line items */}
            <div className="border-t border-hairline pt-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-[11px] uppercase tracking-widest font-bold text-ink/60">Line Items</h3>
                <button onClick={addLine} className="px-3 py-1.5 border border-forest text-forest text-[10px] uppercase tracking-widest font-bold hover:bg-forest hover:text-parchment transition-colors flex items-center gap-1.5">
                  <Plus className="w-3 h-3" /> Add Line
                </button>
              </div>

              <div className="overflow-x-auto">
              <div className="min-w-[680px]">
              <div className="grid grid-cols-12 gap-3 mb-2 px-1 text-[9px] uppercase tracking-widest text-ink/40 font-bold">
                <div className="col-span-4">SKU *</div>
                <div className="col-span-2">Ordered Qty *</div>
                <div className="col-span-2">Unit Cost (₹) *</div>
                <div className="col-span-1">Lot</div>
                <div className="col-span-2">Tax (bps)</div>
                <div className="col-span-1"></div>
              </div>

              <div className="space-y-3">
                {createForm.lines.map((l, idx) => (
                  <div key={idx} className="grid grid-cols-12 gap-3 items-start">
                    <div className="col-span-4">
                      <SkuPicker
                        value={l.skuId}
                        selectedLabel={l.skuLabel}
                        onSelect={(s) => updateLine(idx, { skuId: s.id, skuLabel: `${s.skuCode}${s.name ? ` — ${s.name}` : ''}` })}
                        onClear={() => updateLine(idx, { skuId: '', skuLabel: '' })}
                      />
                    </div>
                    <div className="col-span-2">
                      <input type="number" min={1} step={1} value={l.orderedQty} onChange={(e) => updateLine(idx, { orderedQty: e.target.value })} placeholder="100" className={`${INPUT_SM} text-right tabular-nums`} />
                    </div>
                    <div className="col-span-2">
                      <input type="number" min={0} step="0.01" value={l.unitCostRupees} onChange={(e) => updateLine(idx, { unitCostRupees: e.target.value })} placeholder="49.99" className={`${INPUT_SM} text-right tabular-nums`} />
                    </div>
                    <div className="col-span-1">
                      <input type="number" min={1} step={1} value={l.lotNo} onChange={(e) => updateLine(idx, { lotNo: e.target.value })} placeholder="1" className={`${INPUT_SM} text-right tabular-nums`} />
                    </div>
                    <div className="col-span-2">
                      <input type="number" min={0} max={10000} step={1} value={l.taxBps} onChange={(e) => updateLine(idx, { taxBps: e.target.value })} placeholder="1800" className={`${INPUT_SM} text-right tabular-nums`} />
                    </div>
                    <div className="col-span-1 flex justify-center pt-1.5">
                      <button
                        onClick={() => removeLine(idx)}
                        disabled={createForm.lines.length <= 1}
                        className="text-ink/30 hover:text-terracotta transition-colors disabled:opacity-30 disabled:hover:text-ink/30"
                        title="Remove line"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
              </div>
              </div>

              <p className="text-[9px] text-ink/35 mt-3">Tax in basis points (1800 = 18%) — used only for the PO total. Same SKU may repeat with distinct lot numbers.</p>
            </div>

            <div>
              <label className={`${LABEL} mt-6`}>Notes</label>
              <textarea rows={2} value={createForm.notes} onChange={(e) => setCreateForm({ ...createForm, notes: e.target.value })} className={`${INPUT} resize-none`} />
            </div>

            {/* Live totals + submit */}
            <div className="mt-6 pt-6 border-t border-hairline flex items-center justify-between flex-wrap gap-4">
              <div className="flex gap-8">
                <div>
                  <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold">Subtotal</div>
                  <Money paise={draftTotals.subtotal} className="font-serif font-bold" />
                </div>
                <div>
                  <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold">Tax</div>
                  <Money paise={draftTotals.taxTotal} className="font-serif font-bold" />
                </div>
                <div>
                  <div className="text-[9px] uppercase tracking-widest text-ink/40 font-bold">Grand Total</div>
                  <Money paise={draftTotals.grandTotal} className="font-serif font-bold text-forest" />
                </div>
              </div>
              <div className="flex items-center gap-3">
                <button onClick={() => setOrdersPanel('list')} className="px-6 py-3 border border-hairline text-ink/60 text-[10px] uppercase tracking-widest font-bold hover:border-ink/40 transition-colors">Cancel</button>
                <button onClick={submitCreatePo} disabled={actionLoading || activeSuppliers.length === 0} className="px-8 py-3 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 disabled:opacity-50 transition-colors">
                  {actionLoading ? 'Creating…' : 'Create Draft PO'}
                </button>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* ═══ MODAL: Supplier create / edit ═══ */}
      {showSupplierForm && (
        <div className="fixed inset-0 bg-ink/50 backdrop-blur-[20px] flex items-center justify-center z-50 p-4">
          <div className="bg-alabaster border border-hairline w-full max-w-xl max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-hairline px-8 py-5">
              <h2 className="font-serif text-2xl font-bold flex items-center gap-2">
                <Building2 className="w-5 h-5 text-forest/60" /> {editingSupplier ? 'Edit Supplier' : 'New Supplier'}
              </h2>
              <button onClick={() => setShowSupplierForm(false)} className="text-ink/40 hover:text-ink transition-colors"><X className="w-5 h-5" /></button>
            </div>
            <div className="p-8 space-y-5">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className={LABEL}>Name *</label>
                  <input value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })} className={INPUT} />
                </div>
                <div>
                  <label className={LABEL}>Code</label>
                  <input value={supplierForm.code} onChange={(e) => setSupplierForm({ ...supplierForm, code: e.target.value })} placeholder="SUP-001" className={INPUT} />
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className={LABEL}>Contact Name</label>
                  <input value={supplierForm.contactName} onChange={(e) => setSupplierForm({ ...supplierForm, contactName: e.target.value })} className={INPUT} />
                </div>
                <div>
                  <label className={LABEL}>Email</label>
                  <input type="email" value={supplierForm.email} onChange={(e) => setSupplierForm({ ...supplierForm, email: e.target.value })} className={INPUT} />
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className={LABEL}>Phone</label>
                  <input value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })} className={INPUT} />
                </div>
                <div>
                  <label className={LABEL}>GSTIN</label>
                  <input value={supplierForm.gstin} onChange={(e) => setSupplierForm({ ...supplierForm, gstin: e.target.value })} placeholder="27AAACU1234A1Z5" className={INPUT} />
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="col-span-1">
                  <label className={LABEL}>City</label>
                  <input value={supplierForm.city} onChange={(e) => setSupplierForm({ ...supplierForm, city: e.target.value })} className={INPUT} />
                </div>
                <div className="col-span-1">
                  <label className={LABEL}>State Code</label>
                  <input value={supplierForm.stateCode} onChange={(e) => setSupplierForm({ ...supplierForm, stateCode: e.target.value })} placeholder="27" maxLength={2} className={INPUT} />
                </div>
                <div className="col-span-1">
                  <label className={LABEL}>Lead Time (days)</label>
                  <input type="number" min={0} value={supplierForm.leadTimeDays} onChange={(e) => setSupplierForm({ ...supplierForm, leadTimeDays: e.target.value })} className={INPUT} />
                </div>
              </div>
              <div>
                <label className={LABEL}>Notes</label>
                <textarea rows={2} value={supplierForm.notes} onChange={(e) => setSupplierForm({ ...supplierForm, notes: e.target.value })} className={`${INPUT} resize-none`} />
              </div>
            </div>
            <div className="flex items-center justify-end gap-3 border-t border-hairline px-8 py-5">
              <button onClick={() => setShowSupplierForm(false)} className="px-6 py-3 border border-hairline text-ink/60 text-[10px] uppercase tracking-widest font-bold hover:border-ink/40 transition-colors">Cancel</button>
              <button onClick={submitSupplier} disabled={actionLoading} className="px-8 py-3 bg-forest text-parchment text-[10px] uppercase tracking-widest font-bold hover:bg-forest/90 disabled:opacity-50 transition-colors">
                {actionLoading ? 'Saving…' : editingSupplier ? 'Save Changes' : 'Create Supplier'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
